import './globals.css';
import { Merriweather, Roboto } from 'next/font/google';
import classNames from 'classnames';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Merriweather({
  variable: '--font-roboto',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
});
const merri = Merriweather({
  variable: '--font-merri',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={classNames('font-serif', merri.variable, roboto.variable)}>
      <body>{children}</body>
    </html>
  );
}
